# Generated by Django 4.2.4 on 2023-11-17 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('unit', models.CharField(choices=[('pF', 'Picofaradio'), ('nF', 'Nano faradio'), ('µF', 'Microfaradio'), ('mF', 'Mili faradio'), ('kF', 'Kilo faradio')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.FloatField()),
                ('height', models.FloatField()),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Physical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(max_length=255)),
                ('mount', models.CharField(max_length=255)),
                ('number_of_pins', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Resistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('max_volt', models.FloatField()),
                ('min_volt', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('color', models.CharField(default='Blue')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Volt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('voltage', models.FloatField()),
                ('unit', models.CharField(choices=[('mV', 'milivoltios (mV)'), ('V', 'voltios (V)'), ('kV', 'kilovoltios (kV)'), ('MV', 'megavoltios (MV)')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stock', models.IntegerField()),
                ('moq', models.IntegerField()),
                ('dimensions', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='producto.dimensions')),
                ('distributor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='producto.distributor')),
                ('manufacturer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='producto.manufacturer')),
                ('physical', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='producto.physical')),
                ('technical', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='producto.technical')),
            ],
        ),
    ]
