# Generated by Django 4.2.4 on 2023-11-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technical',
            name='color',
        ),
        migrations.AddField(
            model_name='technical',
            name='pines',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
