# Generated by Django 4.2.4 on 2023-11-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_remove_technical_color_technical_pines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technical',
            name='pines',
            field=models.IntegerField(verbose_name=1),
        ),
    ]
