# Generated by Django 4.2.4 on 2023-11-17 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_alter_technical_pines'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitCapacitance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('unit', models.CharField(choices=[('Picofaradio', 'pF'), ('Nano faradio', 'nF'), ('Microfaradio', 'µF'), ('Mili faradio', 'mF'), ('Kilo faradio', 'kF')], max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnitResistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('unit', models.CharField(choices=[('Ohmios', 'Ω'), ('Kiloohmios', 'kΩ'), ('Megaohmios', 'MΩ'), ('Gigaohmios', 'GΩ'), ('Teraohmios', 'TΩ'), ('Miliohmios', 'mΩ'), ('Microohmios', 'µΩ'), ('Nanoohmios', 'nΩ'), ('Picoohmios', 'pΩ')], max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnitVolt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('voltage', models.FloatField()),
                ('unit', models.CharField(choices=[('milivoltios', 'mV'), ('voltios', 'V'), ('kilovoltios', 'kV'), ('megavoltios', 'MV')], max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Capacitance',
        ),
        migrations.DeleteModel(
            name='Resistance',
        ),
        migrations.DeleteModel(
            name='Volt',
        ),
        migrations.RemoveField(
            model_name='technical',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='technical',
            name='value',
        ),
        migrations.AddField(
            model_name='technical',
            name='capacitance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.unitcapacitance'),
        ),
        migrations.AddField(
            model_name='technical',
            name='resistance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.unitresistance'),
        ),
        migrations.AddField(
            model_name='technical',
            name='voltage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.unitvolt'),
        ),
    ]
