# Generated by Django 4.2.4 on 2023-11-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_alter_component_dimensions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technical',
            name='pines',
            field=models.IntegerField(default=1),
        ),
    ]
