# Generated by Django 4.2.4 on 2023-11-16 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(choices=[('BNA', 'Banco de la Nación Argentina (BNA)'), ('Macro', 'Banco Macro'), ('Galicia', 'Banco Galicia'), ('Santander Rio', 'Banco Santander Río'), ('BBVA Argentina', 'Banco BBVA Argentina'), ('Hipotecario', 'Banco Hipotecario'), ('Ciudad', 'Banco Ciudad'), ('Itau Argentina', 'Banco Itaú Argentina'), ('Patagonia', 'Banco Patagonia'), ('Columbia', 'Banco Columbia')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoTarjeta', models.CharField(choices=[('Visa', 'Visa'), ('MasterCard', 'Mastercard'), ('American Express', 'American Express'), ('Tarjeta Naranja', 'Tarjeta Naranja'), ('Tarjeta Shopping', 'Tarjeta Shopping'), ('Cabal', 'Cabal'), ('Maestro', 'Maestro'), ('Argencard', 'Argencard')], max_length=20)),
                ('BancoEmisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.banco')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persona.persona')),
                ('Registrado', models.DateField()),
                ('Tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tarjeta')),
            ],
            bases=('persona.persona',),
        ),
    ]
