# Generated by Django 4.2.4 on 2023-11-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarjeta',
            old_name='BancoEmisor',
            new_name='banco_emisor',
        ),
        migrations.RenameField(
            model_name='tarjeta',
            old_name='TipoTarjeta',
            new_name='tipo_tarjeta',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Registrado',
            new_name='registrado',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Tarjeta',
            new_name='tarjeta',
        ),
    ]
