# Generated by Django 4.2.4 on 2023-11-27 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_bancoemisor_tarjeta_banco_emisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='banco_emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banco_emisor', to='user.banco'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tarjeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjeta', to='user.tarjeta'),
        ),
    ]
