# Generated by Django 4.2.4 on 2023-11-27 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_tarjeta_banco_emisor_alter_user_tarjeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banco',
            name='banco',
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='banco_emisor',
            field=models.ForeignKey(choices=[('Visa', 'Visa'), ('MasterCard', 'Mastercard'), ('American Express', 'American Express'), ('Tarjeta Naranja', 'Tarjeta Naranja'), ('Tarjeta Shopping', 'Tarjeta Shopping'), ('Cabal', 'Cabal'), ('Maestro', 'Maestro'), ('Argencard', 'Argencard')], on_delete=django.db.models.deletion.CASCADE, related_name='banco_emisor', to='user.banco'),
        ),
    ]
