# Generated by Django 4.2.4 on 2023-11-27 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direccion', to='persona.localidad'),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidad', to='persona.provincia'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direccion', to='persona.direccion'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nacionalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nacionalidad', to='persona.pais'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefono', to='persona.telefono'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincia', to='persona.pais'),
        ),
    ]
