# Generated by Django 4.2.4 on 2023-11-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_alter_direccion_localidad_alter_localidad_provincia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='nombre',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
