# Generated by Django 4.2.4 on 2023-11-27 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_persona_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='nombre',
        ),
    ]
