# Generated by Django 4.2.4 on 2023-11-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_remove_persona_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='nombre',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
