# Generated by Django 4.2.4 on 2023-11-27 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_persona_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='nombre',
            field=models.CharField(choices=[('Ciudad Autónoma de Buenos Aires', 'Ciudad Autónoma de Buenos Aires'), ('La Plata', 'La Plata'), ('Mar del Plata', 'Mar del Plata'), ('Quilmes', 'Quilmes'), ('San Isidro', 'San Isidro'), ('Córdoba', 'Córdoba'), ('Villa María', 'Villa María'), ('Río Cuarto', 'Río Cuarto'), ('Alta Gracia', 'Alta Gracia'), ('Jesús María', 'Jesús María'), ('Santa Fe', 'Santa Fe'), ('Rosario', 'Rosario'), ('Santo Tomé', 'Santo Tomé'), ('Venado Tuerto', 'Venado Tuerto'), ('Rafaela', 'Rafaela'), ('Mendoza', 'Mendoza'), ('San Rafael', 'San Rafael'), ('Godoy Cruz', 'Godoy Cruz'), ('Maipú', 'Maipú'), ('Luján de Cuyo', 'Luján de Cuyo'), ('Salta', 'Salta'), ('San Ramón de la Nueva Orán', 'San Ramón de la Nueva Orán'), ('Tartagal', 'Tartagal'), ('Joaquín V. González', 'Joaquín V. González'), ('Metán', 'Metán')], max_length=255),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidades', to='persona.provincia'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(default='Argentina', max_length=255),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nombre',
            field=models.CharField(choices=[('Buenos Aires', 'Buenos Aires'), ('Córdoba', 'Córdoba'), ('Santa Fe', 'Santa Fe'), ('Mendoza', 'Mendoza'), ('Salta', 'Salta')], max_length=255),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='persona.pais'),
        ),
    ]
