# Generated by Django 4.2.4 on 2023-11-28 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_alter_localidad_nombre_alter_localidad_provincia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='calle',
        ),
        migrations.AlterField(
            model_name='persona',
            name='fechaNacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telefono', to='persona.telefono'),
        ),
    ]
