# Generated by Django 4.2.4 on 2023-11-28 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0008_direccion_calle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='fechaNacimiento',
            new_name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='nacionalidad',
        ),
        migrations.AddField(
            model_name='persona',
            name='pais',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pais', to='persona.pais'),
            preserve_default=False,
        ),
    ]
